# Generated by Django 4.2.11 on 2025-03-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Сообщение обратной связи', 'verbose_name_plural': 'Сообщения обратной связи'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='building',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
