# Generated by Django 4.2.11 on 2025-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запланированнst траты')),
                ('actual_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактические траты')),
            ],
        ),
    ]
