# Generated by Django 4.2.11 on 2025-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.AlterField(
            model_name='cost',
            name='planned_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запланированные траты'),
        ),
    ]
