# Generated by Django 4.2.11 on 2025-03-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_budget_project_delete_cost_budget_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
