# Generated by Django 4.2.11 on 2025-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stage_images/'),
        ),
    ]
