# Generated by Django 4.2.11 on 2025-04-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_stagerating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stagerating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage'),
        ),
    ]
