# Generated by Django 4.2.11 on 2025-04-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0004_alter_stagerating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagerating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='stagerating',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='stages.stage'),
        ),
        migrations.AlterUniqueTogether(
            name='stagerating',
            unique_together={('stage', 'user')},
        ),
    ]
