# Generated by Django 4.2.11 on 2025-05-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_stagerating_updated_at_alter_stagerating_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stage_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stages.stage')),
            ],
        ),
    ]
