# Generated by Django 4.2.11 on 2025-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(verbose_name='Запланированное начало работ')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Фактическое начало работ')),
                ('planned_end_date', models.DateField(verbose_name='Запланированный конец работ')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Фактческий конец работ')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
