# Generated by Django 4.2.11 on 2025-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактический конец работ'),
        ),
    ]
