# Generated by Django 4.2.11 on 2025-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_alter_task_options_alter_task_actual_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.FloatField(default=0.0, help_text='Введите процент завершения (0-100)', verbose_name='Процент завершения'),
        ),
    ]
