# Generated by Django 4.2.11 on 2025-03-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_task_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completion',
        ),
    ]
