# Generated by Django 4.2.11 on 2025-05-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stages', '0006_stagephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
            ],
        ),
        migrations.CreateModel(
            name='StageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.FloatField(verbose_name='План (кол-во)')),
                ('actual_quantity', models.FloatField(default=0, verbose_name='Факт (кол-во)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.material', verbose_name='Материал')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage', verbose_name='Этап')),
            ],
        ),
    ]
